import * as Joi from 'joi';

export const envValidationSchema = Joi.object({
  NODE_ENV: Joi.string()
    .valid('development', 'production', 'test')
    .default('development'),
  PORT: Joi.number().port().default(3000),
  API_PREFIX: Joi.string().default('api/v1'),
  DB_HOST: Joi.string().required(),
  DB_PORT: Joi.number().port().default(3306),
  DB_PUBLIC_PORT: Joi.number().port().default(3307),
  DB_USERNAME: Joi.string().required(),
  DB_PASSWORD: Joi.string().allow('').required(),
  DB_NAME: Joi.string().required(),
  DB_SYNC: Joi.boolean().default(false),
  DB_LOGGING: Joi.boolean().default(false),
  REDIS_HOST: Joi.string().required(),
  REDIS_PORT: Joi.number().port().default(6379),
  REDIS_PUBLIC_PORT: Joi.number().port().default(6380),
  JWT_ACCESS_SECRET: Joi.string().min(16).required(),
  JWT_ACCESS_EXPIRES_IN: Joi.string().required(),
  JWT_REFRESH_SECRET: Joi.string().min(16).required(),
  JWT_REFRESH_EXPIRES_IN: Joi.string().required(),
  AUTH_MAX_FAILED_ATTEMPTS: Joi.number().integer().min(1).default(5),
  AUTH_LOCKOUT_MINUTES: Joi.number().integer().min(1).default(15),
  AUTH_PASSWORD_MIN_LENGTH: Joi.number().integer().min(8).default(8),
  AUTH_PASSWORD_REQUIRE_UPPERCASE: Joi.boolean().default(true),
  AUTH_PASSWORD_REQUIRE_LOWERCASE: Joi.boolean().default(true),
  AUTH_PASSWORD_REQUIRE_NUMBER: Joi.boolean().default(true),
  AUTH_PASSWORD_REQUIRE_SPECIAL: Joi.boolean().default(true),
  AUTH_BOOTSTRAP_ADMIN_MSSQ: Joi.string().allow('').default(''),
  AUTH_BOOTSTRAP_ADMIN_PASSWORD: Joi.string().allow('').default(''),
  AUTH_BOOTSTRAP_ADMIN_FULL_NAME: Joi.string().allow('').default(''),
  AUTH_BOOTSTRAP_ADMIN_ROLE_CODE: Joi.string().allow('').default(''),
});
